name: build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image
      run: docker build -t tuv-x-test . -f Dockerfile.memcheck
    - name: run tests in container
      run: docker run --name test-container -t tuv-x-test bash -c 'make coverage ARGS="--rerun-failed --output-on-failure"'
    - name: copy coverage from container
      run: docker cp test-container:build/coverage.info .
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.info
    - name: build Docker image for MPI tests
      run: docker build -t tuv-x-mpi-test . -f Dockerfile.mpi.memcheck
    - name: run MPI tests in container
      run: docker run -t tuv-x-mpi-test bash -c 'make test ARGS="--rerun-failed --output-on-failure"'
