name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image
      run: docker build -t tuv-x-test .
    - name: run tests in container
      run: docker run --name test-container -t tuv-x-test bash -c 'make test ARGS="--rerun-failed --output-on-failure"'
    - name: build Docker image for MPI tests
      run: docker build -t tuv-x-mpi-test . -f Dockerfile.mpi
    - name: run MPI tests in container
      run: docker run -t tuv-x-mpi-test bash -c 'make test ARGS="--rerun-failed --output-on-failure"'
